dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.7.3
  - smartcontractkit/chainlink@1.9.0
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.7.3'
      - '@chainlink=smartcontractkit/chainlink@1.9.0'
dotenv: .env
networks:
  default: development
  goerli:
    eth_usd_price_feed: "0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e"
    subscriptionId: "1281"
    callbackGasLimit: 500000 # <- showed in Gwei -> 0,0005 ETH
    gasLane: "0x79d3d8832d904592c0bf9818b621522c988bb8b0c05cdc3b15aea1b6e8db0c15"
    vrf_coordinator_v2: "0x2Ca8E0C643bDe4C2E08ab1fA0da3401AdAD7734D"
    verify: True
  mainnet-fork-dev:
    eth_usd_price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
    subscriptionId: "6666"
    callbackGasLimit: 500000 # <- showed in Gwei -> 0,0005 ETH
    gasLane: "0x8af398995b04c28e9951adb9721ef74c74f93e6a478f39e7e0777be13527e7ef"
    vrf_coordinator_v2: "0x271682DEB8C4E0901D1a1550aD2e64D568E69909"
    verify: False
  development:
    eth_usd_price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
    subscriptionId: "6666"
    callbackGasLimit: 500000 # <- showed in Gwei -> 0,0005 ETH
    gasLane: "0x8af398995b04c28e9951adb9721ef74c74f93e6a478f39e7e0777be13527e7ef"
    verify: False
  ganache-local:
    verify: False  
wallets:
  from_key: ${PRIVATE_KEY}
